name: Tests
on: [pull_request]

permissions:
  contents: read

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}

    steps:
      - name: Set up Go 1.19
        uses: actions/setup-go@v3
        with:
          go-version: 1.19

      - name: Check out code
        uses: actions/checkout@v3

      - name: Restore Go modules cache
        uses: actions/cache@v3
        with:
          path: ~/go/pkg/mod
          key: go-${{ runner.os }}-${{ hashFiles('go.mod') }}
          restore-keys: |
            go-${{ runner.os }}-

      - name: Create config.priv.go (bash)
        if: runner.os == 'Linux' || runner.os == 'macOS'
        run: |
          echo "package config; type IConfigPrivate struct {GithubClient string;EncryptKey   string};var Private = IConfigPrivate{GithubClient: \"some\",EncryptKey:\"some\",}" >> ./config/config.priv.go

      - name: Create config.priv.go (Windows)
        if: runner.os == 'Windows'
        run: |
          echo "package config; type IConfigPrivate struct {GithubClient string;EncryptKey string};var Private = IConfigPrivate{GithubClient: `"some`",EncryptKey:`"some`",}" | Out-File -FilePath .\config\config.priv.go

      - name: Download dependencies
        run: go mod download

      # - name: Run tests
      #   run: go test -race ./...

      - name: Build
        run: go build -v ./...